### ISSUE TITLE
Broken in latest Atom Release

### ISSUE THREAD

**Issue by chrishough** [santip/resize-panes#21]
I noticed this package was added to core, so Atom asked to remove it.  After the latest Atom update, both before and after I removed this package.  Resizing the panes via the keyboard has stopped working..  Thoughts on how to fix this?

**Comment by tzniuta** [comment]
yeap. not working with latest one

**Comment by chrishough** [comment]
:cry:  happy to hear it's not only me

**Comment by mnquintana** [comment]
As I mentioned on your comment in atom/atom, there are no keyboard shortcuts for resizing panes in core. It could be added as an enhancement, but since keyboard shortcuts are at a premium Atom probably won't ship with keybindings out of the box for that.

**Comment by vp2177** [comment]
Resizing panes doesn't work with the mouse any more, either.

**Comment by mnquintana** [comment]
@vp2177 I can't reproduce that. Can you reproduce that in safe mode? (`atom --safe`)

**Comment by vp2177** [comment]
Sorry, actually resizing panes works. The only regression is that (I'm on Windows 7) the cursor doesn't change to indicate it's possible as it previously did at the edges.

**Comment by chrishough** [comment]
They used to work with https://github.com/santip/resize-panes @mnquintana but since the latest release broken that package, it looks like they are dead. Also, that functionality can not be installed because core does that now right?

**Comment by chrishough** [comment]
![screen shot 2015-06-16 at 12 53 02 pm](https://cloud.githubusercontent.com/assets/744056/8192988/adad7ff4-1426-11e5-8597-c502a035029c.png)

This package is no longer available in Atom which may be why it is borked...

**Comment by tzniuta** [comment]
hm.. i was on the fedora 21, not windows though

**Comment by chrishough** [comment]
@mnquintana  in reading this again, as this is rendering atom useless for me, you stated it does have shortcuts in your readme:
![screen shot 2015-06-18 at 11 20 19 am](https://cloud.githubusercontent.com/assets/744056/8238678/18013392-15ac-11e5-813b-dabb29672a00.png)

What am I missing here? The shortcuts you state **are not working** :(

**Comment by mnquintana** [comment]
Okay, let's try to clear this up:

This is not my or the Atom team's package - this is a community package generously made by @santip. This package, `resize-panes`, provides keyboard shortcuts for resizing panes. However, this package is now broken because the resizing panes functionality was added to Atom core in https://github.com/atom/atom/pull/5902. 

Atom core's resizing panes functionality does not ship with keyboard shortcuts, and it probably won't get keyboard shortcuts because keyboard shortcuts come at a premium (there aren't many good available keyboard shortcuts, and we want to leave open as many good shortcuts as we can for community packages). 

However, someone could add a command to Atom core for resizing panes, and then you could make keyboard shortcuts of your own in your `keymap.cson`. If that sounds good to you, you can open an issue for adding resize panes commands to Atom core ([atom/atom](https://github.com/atom/atom)).

Does that make sense?

**Comment by chrishough** [comment]
ok, I guess... I will close this and move to that thread.
