### ISSUE TITLE
Package not found in Atom search results

### ISSUE THREAD

**Issue by LeKangouroo** [santip/resize-panes#22]
Hi !

When I search for "resize-panes" in the "Install Packages" panel, this package doesn't show up. This problem doesn't occur with "swap-panes", "move-panes" and "maximize-panes" packages.

I checked everything :
- is it already installed => no
- do I need to update Atom => It's up to date
- do I need to uninstall the "Layout Manager" package => already uninstalled

Did I miss something ?

**Comment by itadakimas** [comment]
Am I the only one who encountered this issue ?

**Comment by dcalhoun** [comment]
Atom has now [deprecated the resize-panes package](https://github.com/atom/atom/blob/v1.0.0/build/deprecated-packages.json#L1275-L1278). This means the package will not be returned when searching. Atom also blocks the package from activating even if you already have resize-panes installed.

The reason Atom did this is because [the abilities of this package have been folded into core](https://github.com/atom/atom/pull/5902). One ability still missing is the [keybindings for resizing panes](https://github.com/atom/atom/issues/7332), but there is a [open PR to add this](https://github.com/atom/atom/pull/7354).

All that said, @santip it'd probably be a good idea to add a note to the top of this project's README stating that the package is deprecated.

**Comment by liuxiong332** [comment]
@itadakimas  the atom editor has integrated this feature internally, so the package `resize-panes` is not necessary.
